db/access.php, lang/en/enrol_apply.php, lang/it/enrol_apply.php, unenrolself.php
Title.
Also, I've corrected a typo in the "en" language files.
=> Added italian translations + implemented the unenrolself feature.

lang/en/enrol_apply.php, lang/en_us/en_us_enrol_apply.php
Language addition (AE) and improvement (EN) by Scott Karren
=> New AE lang and improved EN lang

edit.php, edit_form.php, lib.php, locallib.php
=> Some bugfixes

enroluser.php, lib.php, unenrolself.php, unenroluser.php
Hi emeneo, In order to collaborate with your amazing plugin I have fixed some deprecated used functions.
I hope that you enjoy it ;-)
=> Fixing deprecated functions

version.php
Hello,
This adds $plugin->component to version.php to avoid warnings.
Kind regards,
Daniel
=> Fix component

edit.php
Will now process the course name, which appears in the heading, through Moodle filters in order to handle language tagged course names in a multilingual Moodle environment.
=> APPLY-FixMultilanguage

apply.php, lang/de/enrol_apply.php, lang/en/enrol_apply.php, lib.php, settings.php
This is a "waiting list" feature. It adds the possibility for teachers/managers to put an user enrolment on a waiting list. The user will be notified with a customisable message. The enrolment request will remain in the table with grey background and can be confirmed/canceled later.
This feature is useful when a teacher is not sure if he want to confirm the request at the moment but maybe some days later. If the teacher (without this feature) would keep such a request unanswered the user would get no notification about this.
=> Add waiting list feature.

apply.php, db/install.xml, db/upgrade.php, lib.php, version.php
Store user comment for enrolment application in database to display in the apply table.
=> Store user comment

locallib.php
fixes #35
https://github.com/emeneo/moodle-enrol_apply/issues/35
=> Fix: Use correct instance name.

edit.php, edit_form.php, lib.php
This adds an instance specific setting to enable/disable notifications to teachers when there is a new enrolment application.
=> Add teacher notification setting (sendmailtoteacher) per instance.

edit.php, lib.php
Instance default settings for this plugin were not adopted when created a new instance.
=> Fix: Adopt global instance defaults for new course instance.

db/upgrade.php
=> Fix: error on update due to missing return true in upgrade function

amd/build/manage.min.js, amd/src/manage.js, lang/en/enrol_apply.php, manage.php, manage_table.php, renderer.php, style.css
=> Improve manage table (select menu for actions and toggle all checkbox)

edit_form.php
=> Fix: yes/no options in instance status dropdown switched

version.php
=> Fix version number

db/access.php, lang/en/enrol_apply.php, lib.php
By implementing `enrol_plugin::allow_manage()` an user with `enrol/apply:manage` capability can change an enrolment status, starttime and endtime.
=> Implements enrolments management

edit.php, edit_form.php, lang/en/enrol_apply.php, lib.php, settings.php
Implements enrollib feature which allow to automatically unenrol users, based on an enrolment duration.
Note : you'll need to update the version number in version.php ;)
=> Implements enrolperiod

edit.php
Fixed the issue that new instance was not saved the users should be notified.
=> Fixed notify[] that was not saved when new instance created

lang/en/enrol_apply.php, lang/en_us/en_us_enrol_apply.php, manage.php, renderer.php
Display the header column "Comment"
=> Fixes #90 $instance not initiated

lib.php
Fix to enable enrol method on new created courses
=> Fix to enable enrol method on new created courses (see issues)

classes/privacy/provider.php, lang/en/enrol_apply.php
=> Add privacy provider class
